// Date: 10/29/2015 2:02:15 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package teachstevecode.car;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelCar extends ModelBase
{
  //fields
    ModelRenderer FrontRightWheel;
    ModelRenderer BackRightWheel;
    ModelRenderer FrontLeftWheel;
    ModelRenderer BackLeftWheel;
    ModelRenderer Base;
    ModelRenderer Hood;
    ModelRenderer RightSeg1;
    ModelRenderer RightSeg2;
    ModelRenderer RighttSeg3;
    ModelRenderer RightSeg4;
    ModelRenderer LeftSeg1;
    ModelRenderer LeftSeg2;
    ModelRenderer LeftSeg4;
    ModelRenderer FrontBumper;
    ModelRenderer FrontLeftBumper;
    ModelRenderer FrontRightBumper;
    ModelRenderer LeftSeg3;
    ModelRenderer BackBumper;
    ModelRenderer BackWindow;
    ModelRenderer Roof;
    ModelRenderer Windshield;
    ModelRenderer RightWindow;
    ModelRenderer LeftWindow;
    ModelRenderer FrontRightWindow;
    ModelRenderer FrontLeftWindow;
    ModelRenderer BackLeftWindow;
    ModelRenderer BackRightWindow;
  
  public ModelCar()
  {
    textureWidth = 256;
    textureHeight = 128;
    
      FrontRightWheel = new ModelRenderer(this, 0, 82);
      FrontRightWheel.addBox(0F, 0F, 0F, 2, 6, 6);
      FrontRightWheel.setRotationPoint(8F, 12F, 10F);
      FrontRightWheel.setTextureSize(256, 128);
      FrontRightWheel.mirror = true;
      setRotation(FrontRightWheel, 0F, 0F, 0F);
      BackRightWheel = new ModelRenderer(this, 0, 68);
      BackRightWheel.addBox(0F, 0F, 0F, 2, 6, 6);
      BackRightWheel.setRotationPoint(8F, 12F, -17F);
      BackRightWheel.setTextureSize(256, 128);
      BackRightWheel.mirror = true;
      setRotation(BackRightWheel, 0F, 0F, 0F);
      FrontLeftWheel = new ModelRenderer(this, 17, 82);
      FrontLeftWheel.addBox(0F, 0F, 0F, 2, 6, 6);
      FrontLeftWheel.setRotationPoint(-10F, 12F, 10F);
      FrontLeftWheel.setTextureSize(256, 128);
      FrontLeftWheel.mirror = true;
      setRotation(FrontLeftWheel, 0F, 0F, 0F);
      BackLeftWheel = new ModelRenderer(this, 17, 68);
      BackLeftWheel.addBox(0F, 0F, 0F, 2, 6, 6);
      BackLeftWheel.setRotationPoint(-10F, 12F, -17F);
      BackLeftWheel.setTextureSize(256, 128);
      BackLeftWheel.mirror = true;
      setRotation(BackLeftWheel, 0F, 0F, 0F);
      Base = new ModelRenderer(this, 0, 95);
      Base.addBox(0F, 0F, 0F, 18, 2, 31);
      Base.setRotationPoint(-9F, 15F, -16F);
      Base.setTextureSize(256, 128);
      Base.mirror = true;
      setRotation(Base, 0F, 0F, 0F);
      Hood = new ModelRenderer(this, 100, 100);
      Hood.addBox(0F, 0F, 0F, 20, 1, 10);
      Hood.setRotationPoint(-10F, 10F, 11F);
      Hood.setTextureSize(256, 128);
      Hood.mirror = true;
      setRotation(Hood, -0.2443461F, 0F, 0F);
      RightSeg1 = new ModelRenderer(this, 0, 50);
      RightSeg1.addBox(0F, 0F, 0F, 2, 7, 9);
      RightSeg1.setRotationPoint(6F, 8F, -18F);
      RightSeg1.setTextureSize(256, 128);
      RightSeg1.mirror = true;
      setRotation(RightSeg1, 0F, 0F, 0F);
      RightSeg2 = new ModelRenderer(this, 23, 50);
      RightSeg2.addBox(0F, 0F, 0F, 2, 6, 8);
      RightSeg2.setRotationPoint(6F, 9F, -9F);
      RightSeg2.setTextureSize(256, 128);
      RightSeg2.mirror = true;
      setRotation(RightSeg2, 0F, 0F, 0F);
      RighttSeg3 = new ModelRenderer(this, 44, 50);
      RighttSeg3.addBox(0F, 0F, 0F, 2, 5, 6);
      RighttSeg3.setRotationPoint(6F, 10F, -1F);
      RighttSeg3.setTextureSize(256, 128);
      RighttSeg3.mirror = true;
      setRotation(RighttSeg3, 0F, 0F, 0F);
      RightSeg4 = new ModelRenderer(this, 61, 50);
      RightSeg4.addBox(0F, 0F, 0F, 1, 4, 10);
      RightSeg4.setRotationPoint(7F, 11F, 5F);
      RightSeg4.setTextureSize(256, 128);
      RightSeg4.mirror = true;
      setRotation(RightSeg4, 0F, 0F, 0F);
      LeftSeg1 = new ModelRenderer(this, 0, 33);
      LeftSeg1.addBox(0F, 0F, 0F, 2, 7, 9);
      LeftSeg1.setRotationPoint(-8F, 8F, -18F);
      LeftSeg1.setTextureSize(256, 128);
      LeftSeg1.mirror = true;
      setRotation(LeftSeg1, 0F, 0F, 0F);
      LeftSeg2 = new ModelRenderer(this, 23, 33);
      LeftSeg2.addBox(0F, 0F, 0F, 2, 6, 8);
      LeftSeg2.setRotationPoint(-8F, 9F, -9F);
      LeftSeg2.setTextureSize(256, 128);
      LeftSeg2.mirror = true;
      setRotation(LeftSeg2, 0F, 0F, 0F);
      LeftSeg4 = new ModelRenderer(this, 61, 33);
      LeftSeg4.addBox(0F, 0F, 0F, 1, 4, 10);
      LeftSeg4.setRotationPoint(-8F, 11F, 5F);
      LeftSeg4.setTextureSize(256, 128);
      LeftSeg4.mirror = true;
      setRotation(LeftSeg4, 0F, 0F, 0F);
      FrontBumper = new ModelRenderer(this, 35, 75);
      FrontBumper.addBox(0F, 0F, 0F, 8, 4, 1);
      FrontBumper.setRotationPoint(-4F, 13F, 20F);
      FrontBumper.setTextureSize(256, 128);
      FrontBumper.mirror = true;
      setRotation(FrontBumper, 0F, 0F, 0F);
      FrontLeftBumper = new ModelRenderer(this, 55, 75);
      FrontLeftBumper.addBox(0F, 0F, 0F, 8, 4, 1);
      FrontLeftBumper.setRotationPoint(-8F, 13F, 14F);
      FrontLeftBumper.setTextureSize(256, 128);
      FrontLeftBumper.mirror = true;
      setRotation(FrontLeftBumper, 0F, -0.9424778F, 0F);
      FrontRightBumper = new ModelRenderer(this, 55, 67);
      FrontRightBumper.addBox(0F, 0F, 0F, 8, 4, 1);
      FrontRightBumper.setRotationPoint(8F, 13F, 14F);
      FrontRightBumper.setTextureSize(256, 128);
      FrontRightBumper.mirror = true;
      setRotation(FrontRightBumper, 0F, -2.094395F, 0F);
      LeftSeg3 = new ModelRenderer(this, 44, 33);
      LeftSeg3.addBox(0F, 0F, 0F, 2, 5, 6);
      LeftSeg3.setRotationPoint(-8F, 10F, -1F);
      LeftSeg3.setTextureSize(256, 128);
      LeftSeg3.mirror = true;
      setRotation(LeftSeg3, 0F, 0F, 0F);
      BackBumper = new ModelRenderer(this, 35, 83);
      BackBumper.addBox(0F, 0F, 0F, 16, 7, 3);
      BackBumper.setRotationPoint(-8F, 9F, -19F);
      BackBumper.setTextureSize(256, 128);
      BackBumper.mirror = true;
      setRotation(BackBumper, 0F, 0F, 0F);
      BackWindow = new ModelRenderer(this, 100, 112);
      BackWindow.addBox(0F, 0F, 0F, 16, 1, 15);
      BackWindow.setRotationPoint(-8F, 9F, -19F);
      BackWindow.setTextureSize(256, 128);
      BackWindow.mirror = true;
      setRotation(BackWindow, 0.2617994F, 0F, 0F);
      Roof = new ModelRenderer(this, 162, 118);
      Roof.addBox(0F, 0F, 0F, 16, 1, 9);
      Roof.setRotationPoint(-8F, 5F, -5F);
      Roof.setTextureSize(256, 128);
      Roof.mirror = true;
      setRotation(Roof, 0F, 0F, 0F);
      Windshield = new ModelRenderer(this, 162, 107);
      Windshield.addBox(0F, 0F, 0F, 18, 1, 9);
      Windshield.setRotationPoint(-9F, 5F, 4F);
      Windshield.setTextureSize(256, 128);
      Windshield.mirror = true;
      setRotation(Windshield, -0.6108652F, 0F, 0F);
      RightWindow = new ModelRenderer(this, 0, 16);
      RightWindow.addBox(0F, 0F, 0F, 1, 6, 9);
      RightWindow.setRotationPoint(6F, 6F, -5F);
      RightWindow.setTextureSize(256, 128);
      RightWindow.mirror = true;
      setRotation(RightWindow, 0F, 0F, 0F);
      LeftWindow = new ModelRenderer(this, 0, 0);
      LeftWindow.addBox(0F, 0F, 0F, 1, 6, 9);
      LeftWindow.setRotationPoint(-7F, 6F, -5F);
      LeftWindow.setTextureSize(256, 128);
      LeftWindow.mirror = true;
      setRotation(LeftWindow, 0F, 0F, 0F);
      FrontRightWindow = new ModelRenderer(this, 21, 17);
      FrontRightWindow.addBox(0F, 0F, 0F, 1, 4, 9);
      FrontRightWindow.setRotationPoint(6F, 6F, 4F);
      FrontRightWindow.setTextureSize(256, 128);
      FrontRightWindow.mirror = true;
      setRotation(FrontRightWindow, -0.6108652F, 0F, 0F);
      FrontLeftWindow = new ModelRenderer(this, 21, 0);
      FrontLeftWindow.addBox(0F, 0F, 0F, 1, 4, 9);
      FrontLeftWindow.setRotationPoint(-7F, 6F, 4F);
      FrontLeftWindow.setTextureSize(256, 128);
      FrontLeftWindow.mirror = true;
      setRotation(FrontLeftWindow, -0.6108652F, 0F, 0F);
      BackLeftWindow = new ModelRenderer(this, 43, 0);
      BackLeftWindow.addBox(0F, 0F, 0F, 1, 4, 8);
      BackLeftWindow.setRotationPoint(6F, 8F, -12F);
      BackLeftWindow.setTextureSize(256, 128);
      BackLeftWindow.mirror = true;
      setRotation(BackLeftWindow, 0.2617994F, 0F, 0F);
      BackRightWindow = new ModelRenderer(this, 43, 17);
      BackRightWindow.addBox(0F, 0F, 0F, 1, 4, 8);
      BackRightWindow.setRotationPoint(-7F, 8F, -12F);
      BackRightWindow.setTextureSize(256, 128);
      BackRightWindow.mirror = true;
      setRotation(BackRightWindow, 0.2617994F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    FrontRightWheel.render(f5);
    BackRightWheel.render(f5);
    FrontLeftWheel.render(f5);
    BackLeftWheel.render(f5);
    Base.render(f5);
    Hood.render(f5);
    RightSeg1.render(f5);
    RightSeg2.render(f5);
    RighttSeg3.render(f5);
    RightSeg4.render(f5);
    LeftSeg1.render(f5);
    LeftSeg2.render(f5);
    LeftSeg4.render(f5);
    FrontBumper.render(f5);
    FrontLeftBumper.render(f5);
    FrontRightBumper.render(f5);
    LeftSeg3.render(f5);
    BackBumper.render(f5);
    BackWindow.render(f5);
    Roof.render(f5);
    Windshield.render(f5);
    RightWindow.render(f5);
    LeftWindow.render(f5);
    FrontRightWindow.render(f5);
    FrontLeftWindow.render(f5);
    BackLeftWindow.render(f5);
    BackRightWindow.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
